# Generated by Django 2.1.7 on 2019-03-06 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='student',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='appuser',
            name='teacher',
            field=models.BooleanField(default=False),
        ),
    ]
