# Generated by Django 2.1.7 on 2019-03-06 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('student_courses', '0002_auto_20190306_1800'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appuser',
            name='user_ptr',
        ),
        migrations.DeleteModel(
            name='AppUser',
        ),
    ]
